import Head from 'next/head'
import SvgUploader from './teste'

export default function Home() {
  function handleOnClick(event: React.MouseEvent<SVGElement>): void {
    console.log('oi')
  }
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <SvgUploader onClick={handleOnClick}/>
    </div>
  )
}
